### ISSUE TITLE
Missing HsMG for fract norm computing

### ISSUE THREAD

**Issue by NunDim** [HAZmathTeam/hazmath#13]
Hello to everyone! 
I've installed HAZmath and HAZniCS including HSMG, by customizing the "install_haznics.sh" file; some test cases runs correctly, but others (like demo_3d1d and demo_darcy_stokes_2d) which import "Xii" library from fenics_ii , aren't able to find hsmg packages? Everyone could give me some hints? Have I to set manually this package dependencies? If necessary I can give more details.
Thanks!

**Comment by MiroK** [comment]
Hi @NunDim `hsmg` is not required to run correctly any of the demos and the message is just for information. `hsmg` is a package implementing a different realization (not as efficient as RA) of fractional preconditioners. The code is not really ready to be made public at this point but I can let you know when that changes.
